version: 0.1

env:
  parameter-store:
    ROLE_ARN: "/codebuild/pttp-ci-ima-pipeline/$ENV/assume_role"
    SHARED_SERVICES_ACCOUNT_ID: "/codebuild/staff_device_shared_services_account_id"

phases:
  install:
    commands:
      - echo nope

  build:
    commands:
      - make publish
      - make deploy
      # To uncomment in tandem with the CIDR range change
      # - make deploy_mojo
